---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
setwd("Documents/thesis1830s/corpus35_pr/")

load("data/nkrja_19th_lem.Rda")

per <- read.csv("scr/02_chapter/per_todo.csv")
```

```{r}
glimpse(per)
```

```{r}
per_todo <- per %>% 
  mutate(source = paste(id, "_", PER_ID, year, Vol, Num, sep = "_")) %>%
  select(source, author, first_line) %>% 
  mutate(fl = str_remove_all(first_line, "[[:space:]]|[[:punct:]]"))

head(per_todo)
```

```{r}
found_nkrja <- c19 %>% 
  mutate(fl = str_extract(text_raw, "^.*? \n"),
         fl = str_remove_all(fl, "[[:punct:]]|[[:space:]]")) %>% 
  select(year, author, fl, text_raw) %>% 
  filter(!is.na(fl)) %>% 
  inner_join(per_todo, by = "fl") %>% 
  separate(source, into = c("id", "source"), sep = "__") %>% 
  mutate(text = paste0("author_nkrja:", author.x, 
                       "\nauthor_per:", author.y,
                       "\nsource_per:", source,
                       "\n\ntext:\n", text_raw),
         path = paste0("todo/", id, ".txt")) 

head(found_nkrja)
```

```{r}

setwd("scr/02_chapter/")

for (i in 1:nrow(found_nkrja)) {
  
  write_file(x = found_nkrja$text[i],
             file = found_nkrja$path[i]
             )
}

```
