---
title: "04_2_LDA"
format: html
editor: visual
---

# 4.2. LDA model creation

```{r}
library(tidyverse)
library(tidytext)
library(topicmodels)

theme_set(theme_minimal())
```

```{r, eval = F}
dtm_iamb4_experiment <- readRDS("../../data/ch4/dtm_iamb4_experiment.Rds")
dtm_iamb4_experiment
```

## Build the model

```{r, eval=FALSE}
iamb4_model <- LDA(dtm_iamb4_experiment,
                    k = 75,
                    method = "Gibbs",
                    control = list(seed = 2105, 
                        alpha = 0.5, delta = 0.1))
```

```{r, eval = F}
# retrieve and save beta & gamma probs
beta <- iamb4_model %>% tidy(matrix = "beta")

gamma <- iamb4_model %>% tidy(matrix = "gamma") %>% 
    # separate document id into meaningful columns
    separate(document, into = c("index", "year", "first_line", "formula"), sep = "___") %>% 
    mutate(corpus = str_extract(index, "^\\w"))

```

```{r, eval = F}
save(beta, gamma, file = "../../data/ch4/lda75_output.Rda")
```

## Exploration

```{r}
load("../../data/ch4/lda75_output.Rda")
```

```{r}
glimpse(beta)
glimpse(gamma)
```

```{r}
beta  %>% 
  mutate(topic = as.factor(topic))  %>% 
  group_by(topic) %>%
  top_n(15, beta) %>%
  ungroup() %>%
  ggplot(aes(x = reorder_within(term, beta, topic), 
    y = beta, fill = topic)) +
  scale_x_reordered() + 
  geom_col() +
  coord_flip() +
  facet_wrap(~topic, scales = "free") +
  guides(fill="none") +
  theme(axis.text = element_text(size = 8))

ggsave(filename = "plots/Fig_4-2-0.png", plot = last_plot(), 
      width = 16, height = 14, dpi = 300, bg = "white")
```

Distribution of topic probs

```{r}
topic_probs <- gamma %>%
  group_by(topic) %>%
  summarise(avg_gamma = mean(gamma)) %>% 
  ungroup() %>% 
  arrange(desc(avg_gamma))

print("Most probable topics (avg)")
head(topic_probs, 10)

topic_probs %>% 
  ggplot(aes(reorder(topic,-avg_gamma), avg_gamma)) + geom_col()
```

```{r}
# topic distribution in one text
# gamma %>% filter(corpus == "N")

gamma %>% 
    filter(corpus == "N" & index == "N_1-1") %>% 
    arrange(desc(gamma)) %>% head(10)

gamma %>% 
    filter(corpus == "N" & index == "N_3-1") %>% 
    arrange(desc(gamma)) %>% head(10)
```

```{r}

# top metrical forms
gamma %>% 
  group_by(formula) %>% 
  count(sort = T) %>% 
  head(20)
     
```

```{r}
gamma %>% 
  mutate(year_span = floor(as.numeric(year)/5)*5) %>% 
  group_by(year_span, topic) %>% 
  summarise(gamma_avg = mean(gamma)) %>% 
  top_n(10) %>% 
  ggplot(aes(x = year_span, y = gamma_avg, fill = as.factor(topic))) + geom_col()
```
